PY=python3

tests:
	$(PY) auth_tests.py
	$(PY) pairing_tests.py

pairing:
	$(PY) pairing.py

pairing-tests:
	$(PY) pairing_tests.py


auth:
	$(PY) auth.py

auth-tests:
	$(PY) auth_tests.py

dissect:
	$(PY) dissect.py

